import { StyleSheet } from 'react-native';
import { COLORS } from '../../../constants/theme';

export default StyleSheet.create({
  safeArea:  { flex: 1, backgroundColor: COLORS.primary },

  /* Header */
  header: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: 16,
    paddingVertical:   12,
    backgroundColor:   COLORS.primary,
  },
  backBtn:     { padding: 4, marginRight: 8 },
  backIcon:    { width: 22, height: 22, tintColor: '#fff' },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: '700', color: '#fff' },
  addBtn:      { padding: 6, backgroundColor: COLORS.accent, borderRadius: 8 },
  addIcon:     { width: 18, height: 18, tintColor: '#fff' },

  /* Search */
  searchRow: {
    backgroundColor: COLORS.primary,
    paddingHorizontal: 16,
    paddingBottom:     12,
  },
  searchInput: {
    backgroundColor: '#fff',
    borderRadius:    10,
    paddingHorizontal: 14,
    paddingVertical:   9,
    fontSize:          14,
    color:             '#333',
    elevation:         2,
  },

  /* Filter tabs */
  filterRow: {
    flexDirection:   'row',
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical:   10,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
    gap:               8,
  },
  filterTab: {
    flexDirection:     'row',
    alignItems:        'center',
    paddingHorizontal: 10,
    paddingVertical:   5,
    borderRadius:      20,
    borderWidth:       1.5,
    borderColor:       '#DDD',
    gap:               4,
  },
  filterTabText:       { fontSize: 12, fontWeight: '600', color: '#555' },
  filterTabTextActive: { color: '#fff' },
  filterCount: {
    backgroundColor:  '#F0F0F0',
    borderRadius:     10,
    paddingHorizontal: 6,
    paddingVertical:   1,
  },
  filterCountText: { fontSize: 10, fontWeight: '700', color: '#555' },

  /* List */
  list: { padding: 12, gap: 10, backgroundColor: '#F4F6FA', paddingBottom: 32 },

  /* Lead card */
  leadCard: {
    backgroundColor: '#fff',
    borderRadius:    14,
    padding:         14,
    borderLeftWidth: 4,
    elevation:       3,
    shadowColor:     '#000',
    shadowOpacity:   0.07,
    shadowOffset:    { width: 0, height: 2 },
    shadowRadius:    6,
  },
  leadCardRow:  { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  avatar: {
    width:          40,
    height:         40,
    borderRadius:   20,
    justifyContent: 'center',
    alignItems:     'center',
    marginRight:    12,
  },
  avatarText:  { color: '#fff', fontSize: 14, fontWeight: '700' },
  leadCardInfo:{ flex: 1 },
  leadName:    { fontSize: 15, fontWeight: '700', color: '#1A1A2E' },
  leadPhone:   { fontSize: 12, color: '#888', marginTop: 2 },

  leadCardMeta: {
    flexDirection: 'row',
    alignItems:    'center',
    gap:           8,
    marginBottom:  8,
    flexWrap:      'wrap',
  },
  metaChip: {
    backgroundColor:   '#F0F4FF',
    borderRadius:      6,
    paddingHorizontal: 8,
    paddingVertical:   3,
  },
  metaChipText: { fontSize: 11, color: '#1E4080', fontWeight: '600' },
  timeAgo:      { fontSize: 11, color: '#AAA', marginLeft: 'auto' },

  leadCardFooter: { flexDirection: 'row', justifyContent: 'space-between' },
  budget:         { fontSize: 13, fontWeight: '700', color: '#1E4080' },
  assignedTo:     { fontSize: 11, color: '#999' },

  /* Badge */
  badge: { paddingHorizontal: 10, paddingVertical: 3, borderRadius: 20 },
  badgeText: { fontSize: 11, fontWeight: '700' },

  /* Empty */
  empty:     { alignItems: 'center', paddingVertical: 60 },
  emptyText: { color: '#AAA', fontSize: 14 },

  /* ── Detail Screen ── */
  detailScroll: { backgroundColor: '#F4F6FA', paddingBottom: 40 },

  profileCard: {
    flexDirection:   'row',
    alignItems:      'center',
    margin:          16,
    backgroundColor: '#fff',
    borderRadius:    16,
    padding:         16,
    elevation:       4,
    shadowColor:     '#000',
    shadowOpacity:   0.08,
    shadowOffset:    { width: 0, height: 2 },
    shadowRadius:    8,
  },
  profileAvatar: {
    width:          60,
    height:         60,
    borderRadius:   30,
    justifyContent: 'center',
    alignItems:     'center',
    marginRight:    14,
  },
  profileAvatarText: { fontSize: 22, fontWeight: '800', color: '#fff' },
  profileInfo:       { flex: 1 },
  profileName:       { fontSize: 18, fontWeight: '800', color: '#1A1A2E' },
  profilePhone:      { fontSize: 14, color: '#666', marginTop: 2 },

  stmFlag: {
    backgroundColor: '#FF6F00',
    borderRadius:    10,
    paddingHorizontal: 8,
    paddingVertical:   6,
    alignItems:      'center',
  },
  stmFlagText: { fontSize: 10, fontWeight: '800', color: '#fff', textAlign: 'center' },

  transferBanner: {
    flexDirection:     'row',
    alignItems:        'center',
    backgroundColor:   '#FFF8E1',
    marginHorizontal:  16,
    marginBottom:      12,
    borderRadius:      12,
    paddingHorizontal: 14,
    paddingVertical:   10,
    borderLeftWidth:   4,
    borderLeftColor:   '#FF6F00',
    gap:               8,
  },
  transferBannerIcon: { fontSize: 16 },
  transferBannerText: { fontSize: 13, color: '#555', flex: 1 },

  statusHint: { fontSize: 11, color: '#AAA', marginTop: 8, textAlign: 'center' },

  sectionCard: {
    backgroundColor:  '#fff',
    marginHorizontal: 16,
    marginBottom:     12,
    borderRadius:     14,
    padding:          16,
    elevation:        2,
    shadowColor:      '#000',
    shadowOpacity:    0.05,
    shadowOffset:     { width: 0, height: 1 },
    shadowRadius:     4,
  },
  sectionCardTitle: {
    fontSize:     14,
    fontWeight:   '700',
    color:        COLORS.primary,
    marginBottom: 12,
    textTransform: 'uppercase',
    letterSpacing:  0.5,
  },

  /* Status changer */
  statusRow: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' },
  statusChip: {
    flex:              1,
    paddingVertical:   8,
    borderRadius:      10,
    borderWidth:       1.5,
    alignItems:        'center',
    minWidth:          60,
  },
  statusChipText: { fontSize: 13, fontWeight: '700' },

  /* Info rows */
  infoRow: {
    flexDirection:   'row',
    justifyContent:  'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#F5F5F5',
  },
  infoLabel: { fontSize: 13, color: '#888', flex: 1 },
  infoValue: { fontSize: 13, fontWeight: '600', color: '#333', flex: 1.5, textAlign: 'right' },

  notesText: { fontSize: 14, color: '#444', lineHeight: 21 },

  /* Timeline */
  activityItem: { flexDirection: 'row', marginBottom: 4 },
  timelineLine:  { alignItems: 'center', width: 20, marginRight: 12 },
  timelineDot: {
    width:        10,
    height:       10,
    borderRadius: 5,
    backgroundColor: COLORS.accent,
    marginTop:    3,
  },
  timelineConnector: {
    flex:            1,
    width:           2,
    backgroundColor: '#E0E0E0',
    marginTop:       2,
    marginBottom:    -4,
    minHeight:       28,
  },
  activityContent: { flex: 1, paddingBottom: 16 },
  activityType:    { fontSize: 12, fontWeight: '700', color: COLORS.primary, marginBottom: 2 },
  activityNote:    { fontSize: 13, color: '#333', marginBottom: 2 },
  activityTime:    { fontSize: 11, color: '#AAA' },

  /* ── Add Lead Form ── */
  formScroll:  { backgroundColor: '#F4F6FA', padding: 16, paddingBottom: 40, gap: 12 },
  formCard: {
    backgroundColor: '#fff',
    borderRadius:    14,
    padding:         16,
    elevation:       2,
    shadowColor:     '#000',
    shadowOpacity:   0.05,
    shadowOffset:    { width: 0, height: 1 },
    shadowRadius:    4,
    gap:             4,
  },
  formSection: {
    fontSize:     13,
    fontWeight:   '700',
    color:        COLORS.primary,
    marginBottom: 8,
    textTransform: 'uppercase',
    letterSpacing:  0.5,
  },

  field:       { marginBottom: 12 },
  fieldLabel:  { fontSize: 13, fontWeight: '600', color: '#555', marginBottom: 6 },
  required:    { color: COLORS.accent },
  input: {
    backgroundColor:   '#F7F8FA',
    borderRadius:      10,
    borderWidth:       1,
    borderColor:       '#E8E8E8',
    paddingHorizontal: 14,
    paddingVertical:   11,
    fontSize:          14,
    color:             '#333',
  },
  textarea: { height: 90, paddingTop: 11 },

  pickerBtn: {
    backgroundColor:   '#F7F8FA',
    borderRadius:      10,
    borderWidth:       1,
    borderColor:       '#E8E8E8',
    paddingHorizontal: 14,
    paddingVertical:   11,
    flexDirection:     'row',
    justifyContent:    'space-between',
    alignItems:        'center',
  },
  pickerValue:       { fontSize: 14, color: '#333' },
  pickerPlaceholder: { fontSize: 14, color: '#BBB' },
  pickerArrow:       { fontSize: 20, color: '#AAA', marginTop: -2 },

  modalOverlay: {
    flex:            1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent:  'flex-end',
  },
  pickerSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius:  20,
    borderTopRightRadius: 20,
    padding:          16,
    maxHeight:        '60%',
  },
  pickerSheetTitle: {
    fontSize:     16,
    fontWeight:   '700',
    color:        '#1A1A2E',
    marginBottom: 12,
    textAlign:    'center',
  },
  pickerOption: {
    paddingVertical:   14,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  pickerOptionText: { fontSize: 15, color: '#333' },

  submitBtn: {
    backgroundColor: COLORS.primary,
    borderRadius:    14,
    paddingVertical: 15,
    alignItems:      'center',
    elevation:       4,
    shadowColor:     COLORS.primary,
    shadowOpacity:   0.3,
    shadowOffset:    { width: 0, height: 4 },
    shadowRadius:    8,
  },
  submitBtnText: { color: '#fff', fontSize: 16, fontWeight: '700' },

  /* ── Filter icon button ── */
  filterIconBtn: {
    width:          34,
    height:         34,
    borderRadius:   8,
    borderWidth:    1.5,
    borderColor:    'rgba(255,255,255,0.5)',
    justifyContent: 'center',
    alignItems:     'center',
  },
  filterIconBtnActive: {
    backgroundColor: COLORS.accent,
    borderColor:     COLORS.accent,
  },
  filterIconText: { fontSize: 16, color: '#fff' },
  filterBadge: {
    position:        'absolute',
    top:             -5,
    right:           -5,
    width:           16,
    height:          16,
    borderRadius:    8,
    backgroundColor: '#FF3D00',
    justifyContent:  'center',
    alignItems:      'center',
  },
  filterBadgeText: { fontSize: 9, fontWeight: '800', color: '#fff' },

  /* Active filter chips strip (below status tabs) */
  activeFiltersRow: {
    flexDirection:     'row',
    flexWrap:          'wrap',
    paddingHorizontal: 12,
    paddingBottom:     8,
    gap:               8,
    backgroundColor:   '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  activeFilterChip: {
    backgroundColor:   '#EEF2FF',
    borderRadius:      20,
    paddingHorizontal: 10,
    paddingVertical:   5,
    borderWidth:       1,
    borderColor:       COLORS.primary,
  },
  activeFilterChipText: { fontSize: 12, fontWeight: '600', color: COLORS.primary },

  /* Filter bottom sheet */
  filterSheet: {
    backgroundColor:      '#fff',
    borderTopLeftRadius:  24,
    borderTopRightRadius: 24,
    paddingBottom:        32,
    paddingTop:           12,
    maxHeight:            '85%',
  },
  fsHeader: {
    flexDirection:    'row',
    justifyContent:   'space-between',
    alignItems:       'center',
    paddingHorizontal: 20,
    marginBottom:     16,
  },
  fsTitle:   { fontSize: 18, fontWeight: '800', color: '#1A1A2E' },
  fsClear:   { fontSize: 13, fontWeight: '600', color: COLORS.accent },
  fsSection: { paddingHorizontal: 20, marginBottom: 20 },
  fsSectionTitle: {
    fontSize:      12,
    fontWeight:    '700',
    color:         '#999',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    marginBottom:  10,
  },
  fsChips:   { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  fsChip: {
    paddingHorizontal: 12,
    paddingVertical:   7,
    borderRadius:      20,
    borderWidth:       1.5,
    borderColor:       '#DDD',
    backgroundColor:   '#FAFAFA',
  },
  fsChipText:  { fontSize: 13, fontWeight: '600', color: '#555' },
  fsFooter: {
    flexDirection:    'row',
    paddingHorizontal: 20,
    paddingTop:        14,
    gap:              12,
  },
  fsCancelBtn: {
    flex:            1,
    paddingVertical: 14,
    borderRadius:    12,
    borderWidth:     1.5,
    borderColor:     '#DDD',
    alignItems:      'center',
  },
  fsCancelText: { fontSize: 15, fontWeight: '600', color: '#555' },
  fsApplyBtn: {
    flex:            2,
    paddingVertical: 14,
    borderRadius:    12,
    backgroundColor: COLORS.primary,
    alignItems:      'center',
    elevation:       3,
    shadowColor:     COLORS.primary,
    shadowOpacity:   0.3,
    shadowOffset:    { width: 0, height: 3 },
    shadowRadius:    6,
  },
  fsApplyText: { fontSize: 15, fontWeight: '700', color: '#fff' },

  /* ── StatusChangeSheet ── */
  sheetOverlay: { flex: 1, justifyContent: 'flex-end' },
  sheetBackdrop: {
    position:        'absolute',
    top:             0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.45)',
  },
  statusSheet: {
    backgroundColor:      '#fff',
    borderTopLeftRadius:  24,
    borderTopRightRadius: 24,
    padding:              20,
    paddingBottom:        32,
  },
  sheetHandle: {
    width:           40,
    height:          4,
    borderRadius:    2,
    backgroundColor: '#DDD',
    alignSelf:       'center',
    marginBottom:    16,
  },
  statusSheetHeader: {
    flexDirection:  'row',
    alignItems:     'center',
    gap:            10,
    marginBottom:   16,
  },
  statusSheetTitle: { fontSize: 18, fontWeight: '800', color: '#1A1A2E' },
  noteInputLabel:   { fontSize: 13, fontWeight: '600', color: '#555', marginBottom: 6 },
  noteOptional:     { fontWeight: '400', color: '#AAA' },
  noteInput: {
    backgroundColor:   '#F7F8FA',
    borderRadius:      10,
    borderWidth:       1,
    borderColor:       '#E8E8E8',
    paddingHorizontal: 12,
    paddingVertical:   10,
    fontSize:          14,
    color:             '#333',
    minHeight:         80,
    marginBottom:      16,
  },
  sheetFooter:     { flexDirection: 'row', gap: 12 },
  sheetCancelBtn: {
    flex:            1,
    paddingVertical: 14,
    borderRadius:    12,
    borderWidth:     1.5,
    borderColor:     '#DDD',
    alignItems:      'center',
  },
  sheetCancelText:  { fontSize: 15, fontWeight: '600', color: '#555' },
  sheetConfirmBtn: {
    flex:            2,
    paddingVertical: 14,
    borderRadius:    12,
    alignItems:      'center',
    elevation:       3,
  },
  sheetConfirmText: { fontSize: 15, fontWeight: '700', color: '#fff' },
});
