const fs = require('fs');
const path = require('path');
const {
  AndroidConfig,
  withAndroidColors,
  withAndroidColorsNight,
  withAndroidStyles,
  withDangerousMod,
} = require('expo/config-plugins');

const COLOR_NAME = 'splashscreen_background';
const DEFAULT_COLOR = '#000000';

// Keeps one launch colour from the system splash through to the first JS frame.
//
// Prebuild leaves AppTheme without an android:windowBackground, and MainActivity
// swaps the window to AppTheme in onCreate (expo-splash-screen needs that), so
// the window falls back to Theme.AppCompat.Light's white and flashes between the
// launcher icon and the splash screen. Android 12+ draws its own launch screen
// and ignores windowBackground altogether, so the colour has to be repeated as
// windowSplashScreenBackground in values-v31.
//
// The colour must stay equal to the first colour Splashscreen.js paints
// (COLORS.black) — that screen carries the same colour as its own background so
// its gradient, a native view that lands a frame or two late, never reveals the
// window underneath.
const V31_STYLES = (colorName) => `<resources>
  <!-- Generated by plugins/withLaunchBackground.js — Android 12+ ignores
       windowBackground for the launch screen and reads this instead. -->
  <style name="Theme.App.SplashScreen" parent="AppTheme">
    <item name="android:windowSplashScreenBackground">@color/${colorName}</item>
  </style>
</resources>
`;

const withLaunchBackground = (config, props = {}) => {
  const color = props.backgroundColor || config.splash?.backgroundColor || DEFAULT_COLOR;
  const nightColor = props.backgroundColorNight || color;

  config = withAndroidColors(config, (cfg) => {
    cfg.modResults = AndroidConfig.Colors.assignColorValue(cfg.modResults, {
      name: COLOR_NAME,
      value: color,
    });
    return cfg;
  });

  config = withAndroidColorsNight(config, (cfg) => {
    cfg.modResults = AndroidConfig.Colors.assignColorValue(cfg.modResults, {
      name: COLOR_NAME,
      value: nightColor,
    });
    return cfg;
  });

  config = withAndroidStyles(config, (cfg) => {
    cfg.modResults = AndroidConfig.Styles.assignStylesValue(cfg.modResults, {
      add: true,
      name: 'android:windowBackground',
      value: `@color/${COLOR_NAME}`,
      parent: AndroidConfig.Styles.getAppThemeGroup(),
    });
    return cfg;
  });

  // There is no mod for values-v31, so the file is written directly.
  config = withDangerousMod(config, ['android', async (cfg) => {
    const dir = path.join(cfg.modRequest.platformProjectRoot, 'app', 'src', 'main', 'res', 'values-v31');
    await fs.promises.mkdir(dir, { recursive: true });
    await fs.promises.writeFile(path.join(dir, 'styles.xml'), V31_STYLES(COLOR_NAME), 'utf8');
    return cfg;
  }]);

  return config;
};

module.exports = withLaunchBackground;
