const { withGradleProperties, withAppBuildGradle } = require('expo/config-plugins');

// The release APK shipped four ABIs — arm64-v8a, armeabi-v7a, x86 and x86_64 —
// and the two x86 ones are emulator-only: 43 MB of a 102 MB download that no
// phone can ever execute. Phones get the two ARM slices and nothing else.
//
// This lives in a plugin rather than android/gradle.properties because android/
// is gitignored and regenerated by `expo prebuild`, which would drop the edit.
const ARCHITECTURES = 'armeabi-v7a,arm64-v8a';

function setProp(config, key, value) {
  const existing = config.modResults.find((i) => i.type === 'property' && i.key === key);
  if (existing) existing.value = value;
  else config.modResults.push({ type: 'property', key, value });
}

// The release build was signed with the debug keystore — the key Android ships
// with, which everyone has. That blocks Play Store submission and means anyone
// can sign an "update" for this package. Release now uses a real upload key when
// one is configured (NEXORA_STORE_FILE and friends, kept in ~/.gradle/
// gradle.properties, never in the repo) and falls back to debug when it isn't,
// so a machine without the key can still produce a test build.
function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.contents.includes('NEXORA_STORE_FILE')) return cfg;
    cfg.modResults.contents = cfg.modResults.contents.replace(
      /signingConfigs \{/,
      `signingConfigs {
        release {
            if (project.hasProperty('NEXORA_STORE_FILE')) {
                storeFile file(NEXORA_STORE_FILE)
                storePassword NEXORA_STORE_PASSWORD
                keyAlias NEXORA_KEY_ALIAS
                keyPassword NEXORA_KEY_PASSWORD
            }
        }`,
    ).replace(
      /(release \{\n\s+\/\/ Caution![^\n]*\n\s+\/\/[^\n]*\n\s+)signingConfig signingConfigs\.debug/,
      '$1signingConfig project.hasProperty(\'NEXORA_STORE_FILE\') ? signingConfigs.release : signingConfigs.debug',
    );
    return cfg;
  });
}

module.exports = function withAndroidArchitectures(config) {
  config = withReleaseSigning(config);
  return withGradleProperties(config, (cfg) => {
    setProp(cfg, 'reactNativeArchitectures', ARCHITECTURES);
    // R8 shrinks the 29 MB of dex the release build otherwise ships whole.
    setProp(cfg, 'android.enableMinifyInReleaseBuilds', 'true');
    setProp(cfg, 'android.enableShrinkResourcesInReleaseBuilds', 'true');
    return cfg;
  });
};
