export const DASHBOARD_REQUEST = 'DASHBOARD_REQUEST';
export const DASHBOARD_SUCCESS = 'DASHBOARD_SUCCESS';
export const DASHBOARD_FAILURE = 'DASHBOARD_FAILURE';

export const MONTHLY_ATTENDANCE_REQUEST = 'MONTHLY_ATTENDANCE_REQUEST';
export const MONTHLY_ATTENDANCE_SUCCESS = 'MONTHLY_ATTENDANCE_SUCCESS';
export const MONTHLY_ATTENDANCE_FAILURE = 'MONTHLY_ATTENDANCE_FAILURE';
