export const LEAVE_ACTION_REQUEST = 'LEAVE_ACTION_REQUEST';
export const LEAVE_ACTION_SUCCESS = 'LEAVE_ACTION_SUCCESS';
export const LEAVE_ACTION_FAILURE = 'LEAVE_ACTION_FAILURE';
export const LEAVE_ACTION_RESET   = 'LEAVE_ACTION_RESET';
