export const LEAVE_BALANCE_REQUEST = 'LEAVE_BALANCE_REQUEST';
export const LEAVE_BALANCE_SUCCESS = 'LEAVE_BALANCE_SUCCESS';
export const LEAVE_BALANCE_FAILURE = 'LEAVE_BALANCE_FAILURE';
export const LEAVE_BALANCE_REFRESH = 'LEAVE_BALANCE_REFRESH';
