export const PRESALES_DASHBOARD_REQUEST = 'PRESALES_DASHBOARD_REQUEST';
export const PRESALES_DASHBOARD_SUCCESS = 'PRESALES_DASHBOARD_SUCCESS';
export const PRESALES_DASHBOARD_FAILURE = 'PRESALES_DASHBOARD_FAILURE';

export const PRESALES_LEADS_REQUEST = 'PRESALES_LEADS_REQUEST';
export const PRESALES_LEADS_SUCCESS = 'PRESALES_LEADS_SUCCESS';
export const PRESALES_LEADS_FAILURE = 'PRESALES_LEADS_FAILURE';

export const PRESALES_PROJECTS_REQUEST = 'PRESALES_PROJECTS_REQUEST';
export const PRESALES_PROJECTS_SUCCESS = 'PRESALES_PROJECTS_SUCCESS';
export const PRESALES_PROJECTS_FAILURE = 'PRESALES_PROJECTS_FAILURE';

export const PRESALES_TEAM_REQUEST = 'PRESALES_TEAM_REQUEST';
export const PRESALES_TEAM_SUCCESS = 'PRESALES_TEAM_SUCCESS';
export const PRESALES_TEAM_FAILURE = 'PRESALES_TEAM_FAILURE';
