export const REQUEST_LEAVE_REQUEST = 'REQUEST_LEAVE_REQUEST';
export const REQUEST_LEAVE_SUCCESS = 'REQUEST_LEAVE_SUCCESS';
export const REQUEST_LEAVE_FAILURE = 'REQUEST_LEAVE_FAILURE';
export const REQUEST_LEAVE_RESET   = 'REQUEST_LEAVE_RESET';
